### ISSUE TITLE
运行Shell脚本任务

### ISSUE THREAD

**Issue by perillaroc** [perillaroc/takler#23]
执行 shell 命令，运行 ShellScriptTask。

Shell 命令保存在 `TAKLER_SHELL_JOB_CMD` 中。

运行脚本方式：

- 直接运行
- 提交到队列调度系统 Slurm 中（后续 issue）

**Comment by perillaroc** [comment]
旧版运行方法：两次 fork

- `os.fork()`
- `os.fork()`
  - `os.execl()` + `os.exit()`

**Comment by perillaroc** [comment]
使用协程后执行 `fork` 会导致子程序的协程 RuntimeError，无法终止第一个 fork 的进程导致形成僵尸进程。

脚本出错：

```
Exception ignored in: <function Server.__del__ at 0x2aeb0cf043a0>
Traceback (most recent call last):
  File "/g11/wangdp/lang/python/anaconda3/envs/takler/lib/python3.10/site-packages/grpc/aio/_server.py", line 170, in __del__
    cygrpc.schedule_coro_threadsafe(
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/common.pyx.pxi", line 118, in grpc._cython.cygrpc.schedule_coro_threadsafe
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/common.pyx.pxi", line 110, in grpc._cython.cygrpc.schedule_coro_threadsafe
  File "/g11/wangdp/lang/python/anaconda3/envs/takler/lib/python3.10/asyncio/base_events.py", line 436, in create_task
    self._check_closed()
  File "/g11/wangdp/lang/python/anaconda3/envs/takler/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'AioServer.shutdown' was never awaited
```

进程情况：

```
UID         PID   PPID  C STIME TTY          TIME CMD
wangdp     9930 121295  0 01:57 pts/12   00:00:00 /g11/wangdp/lang/python/anaconda3/envs/takler/bin/python -u /g11/wangdp/project/work/workflow/takler-project/takler/playground/tasks/shell/02-flow/run_
wangdp    10041   9930 99 01:57 ?        00:00:59 /g11/wangdp/lang/python/anaconda3/envs/takler/bin/python -u /g11/wangdp/project/work/workflow/takler-project/takler/playground/tasks/shell/02-flow/run_
wangdp    10042  10041  0 01:57 ?        00:00:00 [sh] <defunct>
```

尝试两种方案：

- 强制关闭所有异步函数
- 使用 AnyIO 的 subprogress 运行命令，不再使用 fork

**Comment by perillaroc** [comment]
## 方案一 ❌

加入异步函数关闭 `stop` 函数，fork 新进程中退出会导致 grpc 服务退出，使 client 失效

**Comment by perillaroc** [comment]
## 方案二 :alembic:

使用 `anyio.run_process` 在异步函数中创建子进程。

问题：子命令不再是独立进程

```py
import asyncio
from anyio import run_process

def spwan(self, command: str):
    async def run_shell_command():
        await run_process(["/bin/sh", "-c", command])
    loop = asyncio.get_running_loop()
    t = loop.create_task(run_shell_command())
```
